import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import 'bootstrap/dist/css/bootstrap.min.css';
import NavBar from '@/components/Navbar';
import Footer from '@/components/Footer';
import Providers from './providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Campus Clubhouse',
  description: 'Generated by ics-software-engineering.github.io',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${inter.className} wrapper d-flex flex-column min-vh-100`}>
        <Providers>
          <NavBar />
          <main className="flex-grow-1">{children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
